login:
    path: /login
    controller: App\Controller\SecurityController::login

login_clients:
    path: /login-clients
    controller: App\Controller\SecurityController::loginClients

logout:
    path: /logout    

index:
    path: /
    controller: App\Controller\HomeController::html

index_info:
    path: /info/
    controller: App\Controller\HomeController::info

index_translate:
    path: /translate
    controller: App\Controller\TranslationController::translate

index_user_translate:
    path: /userTranslation/{lang}/{page}
    controller: App\Controller\HomeController::userTranslation


index_help_improve:
    path: /help-improve/
    controller: App\Controller\HelpImproveController::helpImprove

set_booking:
    path: /booking
    controller: App\Controller\HomeController::setBooking
    #condition: 'request.isXmlHttpRequest()'
    #methods: [POST]

home_get_charge:
    path: /home-get-charge
    controller: App\Controller\HomeController::onlineGetCharge
    methods: [POST]

###
# FEEDBACK
###
send_feedback:
    path: /send-feedback/
    controller: App\Controller\FeedbackController::sendFeedback
    methods: [POST]
    condition: 'request.isXmlHttpRequest()'


admin_feedback_list:
    path: /admin-feedback-list/
    controller: App\Controller\FeedbackController::list

###
# REPORT ISSUE
###

send_report_issue:
    path: /send-report-issue/
    controller: App\Controller\HelpImproveController::sendReportIssue
    methods: [POST]
    condition: 'request.isXmlHttpRequest()'

###
# CRON LOGS
###
list_cron:
    path: /list-cron/
    controller: App\Controller\CronController::listCron
    methods: [POST]
    condition: 'request.isXmlHttpRequest()'

###
# AVAILABLE
###
index_available:
    path: /index-available/
    controller: App\Controller\BookingController::getAvailable
    #condition: 'request.isXmlHttpRequest()'
index_admin:
    path: /admin/
    controller: App\Controller\AdminController::html


####
# template ajax load with twig
####

admin_dashboard:
    path: /admin-dashboard/
    controller: App\Controller\AdminController::adminDashboard


##
# COMPANY
##

admin_company_new:
    path: /admin-company-new/
    controller: App\Controller\CompanyController::companyNew

admin_company_add:
    path: /admin-company-add/
    controller: App\Controller\CompanyController::companyAdd
    #condition: 'request.isXmlHttpRequest()'

admin_company_list:
    path: /admin-company-list/
    controller: App\Controller\CompanyController::CompanyList

admin_company_show_edit:
    path: /admin-company-show-edit/
    controller: App\Controller\CompanyController::companyShowEdit
    condition: 'request.isXmlHttpRequest()'

admin_company_edit:
    path: /admin-company-edit/
    controller: App\Controller\CompanyController::companyEdit
    condition: 'request.isXmlHttpRequest()'



##
# CATEGORIES
##

admin_category_new:
    path: /admin-category-new/
    controller: App\Controller\CategoryController::categoryNew

admin_category_add:
    path: /admin-category-add/
    controller: App\Controller\CategoryController::categoryAdd
    #condition: 'request.isXmlHttpRequest()'

admin_category_list:
    path: /admin-category-list/
    controller: App\Controller\CategoryController::categoryList

admin_category_show_edit:
    path: /admin-category-show-edit/
    controller: App\Controller\CategoryController::categoryShowEdit
    condition: 'request.isXmlHttpRequest()'

admin_category_edit:
    path: /admin-category-edit/
    controller: App\Controller\CategoryController::categoryEdit
    condition: 'request.isXmlHttpRequest()'

admin_category_delete:
    path: /admin-category-delete/
    controller: App\Controller\CategoryController::categoryDelete
    #condition: 'request.isXmlHttpRequest()'

admin_category_order:
    path: /admin-category-order/
    controller: App\Controller\CategoryController::categoryOrder
    #condition: 'request.isXmlHttpRequest()'

category_payment:
    path: /category-payment
    controller: App\Controller\CategoryController::categoryPayment
    methods: [POST]
    condition: 'request.isXmlHttpRequest()'

##
# BOOKINGS ADMIN EVENTS
##

admin_booking:
    path: /admin-booking/
    controller: App\Controller\AdminController::adminBooking

admin_booking_search:
    path: /admin-booking-search
    controller: App\Controller\AdminController::adminBookingSearch
    condition: 'request.isXmlHttpRequest()'

admin_booking_set_status:
    path: /admin-booking-set-status/
    controller: App\Controller\AdminController::adminBookingSetStatus
    #condition: 'request.isXmlHttpRequest()'

admin_booking_send_status:
    path: /admin-booking-send-status/
    controller: App\Controller\AdminController::adminBookingSendStatus
    #condition: 'request.isXmlHttpRequest()'

admin_booking_validate_user:
    path: /admin/booking/validate-user/
    controller: App\Controller\AdminController::bookingValidateUser
    condition: 'request.isXmlHttpRequest()'
    methods: [POST]

charge_payment:
    path: /charge-payment
    controller: App\Controller\AdminController::paymentStripe
    condition: 'request.isXmlHttpRequest()'
    methods: [POST]

##
# AVAILABLE
##

admin_available:
    path: /admin-available/
    controller: App\Controller\AvailableController::adminAvailable

admin_available_new:
    path: /admin-available-new/
    controller: App\Controller\AvailableController::adminAvailableNew

admin_available_create:
    path: /admin-available-create/
    controller: App\Controller\AvailableController::adminAvailableCreate

admin_available_list:
    path: /admin-available-list/
    controller: App\Controller\AvailableController::adminAvailableList

admin_available_edit:
    path: /admin-available-edit/
    controller: App\Controller\AvailableController::adminAvailableEdit

admin_available_delete:
    path: /admin-available-delete/
    controller: App\Controller\AvailableController::adminAvailableDelete

admin_available_resources_actions:
    path: /admin-available-resources-actions/
    controller: App\Controller\AvailableController::adminAvailableResourcesActions

##
# EASY TEXT
##

admin_easy_text:
    path: /admin-easy-text/
    controller: App\Controller\EasyTextController::EasyText
    #condition: 'request.isXmlHttpRequest()'

admin_easy_text_delete:
    path: /admin-easy-text-delete/
    controller: App\Controller\EasyTextController::EasyTextDelete

##
# RGPD
##

admin_rgpd:
    path: /admin-rgpd/
    controller: App\Controller\RgpdController::rgpd
    #condition: 'request.isXmlHttpRequest()'

admin_rgpd_delete:
    path: /admin-easy-rgpd-delete/
    controller: App\Controller\RgpdController::rgpdDelete

admin_rgpd_edit:
    path: /admin-easy-rgpd-edit/
    controller: App\Controller\RgpdController::rgpdEdit

index_rgpd:
    path: /index-rgpd/
    controller: App\Controller\RgpdController::rgpdShow
    #condition: 'request.isXmlHttpRequest()'


##
# ABOUT-US
##

admin_about_us:
    path: /admin-about-us/
    controller: App\Controller\AboutUsController::aboutUs
    #condition: 'request.isXmlHttpRequest()'

admin_about_us_delete:
    path: /admin-about-us-delete/
    controller: App\Controller\AboutUsController::aboutUsDelete

admin_about_us_edit:
    path: /admin-about-us-edit/
    controller: App\Controller\AboutUsController::aboutUsEdit

index_about_us:
    path: /index-about-us/
    controller: App\Controller\AboutUsController::aboutUsShow
    #condition: 'request.isXmlHttpRequest()'


##
# TERMS CONDITIONS
##

admin_terms:
    path: /admin-terms/
    controller: App\Controller\TermsConditionsController::terms
    #condition: 'request.isXmlHttpRequest()'

admin_terms_delete:
    path: /admin-easy-terms-delete/
    controller: App\Controller\TermsConditionsController::termsDelete

admin_terms_edit:
    path: /admin-easy-terms-edit/
    controller: App\Controller\TermsConditionsController::termsEdit

index_terms:
    path: /index-terms/
    controller: App\Controller\TermsConditionsController::termsShow
    #condition: 'request.isXmlHttpRequest()'


##
# BLOCK DATES
##

admin_block_date_edit:
    path: /admin-block-date-edit/
    controller: App\Controller\BlockDateController::adminBlockDateEdit

admin_block_date_set_values:
    path: /admin-block-date-set-values/
    controller: App\Controller\BlockDateController::adminBlockDateSetValues
    condition: 'request.isXmlHttpRequest()'

##
# WARNING
##

admin_warning:
    path: /admin-warning/
    controller: App\Controller\WarningController::adminWarning

admin_warning_edit:
    path: /admin-warning-edit/
    controller: App\Controller\WarningController::adminWarningEdit


##
# GALLERY
##

admin_gallery:
    path: /admin-gallery/
    controller: App\Controller\GalleryController::gallery

admin_gallery_list:
    path: /admin-gallery-list/
    controller: App\Controller\GalleryController::galleryList

admin_gallery_new:
    path: /admin-gallery-new/
    controller: App\Controller\GalleryController::galleryNew

admin_gallery_delete:
    path: /admin-gallery-delete/
    controller: App\Controller\GalleryController::galleryDelete

admin_gallery_add:
    path: /admin-gallery-add/
    controller: App\Controller\GalleryController::galleryAdd
    #condition: 'request.isXmlHttpRequest()'

admin_gallery_show_edit:
    path: /admin-gallery-show-edit/
    controller: App\Controller\GalleryController::galleryShowEdit
    #condition: 'request.isXmlHttpRequest()'

admin_gallery_edit:
    path: /admin-gallery-edit/
    controller: App\Controller\GalleryController::galleryEdit
    #condition: 'request.isXmlHttpRequest()'

##
# USERS
##

user_list:
    path: /user-list/
    controller: App\Controller\UserController::listUser

status_user:
    path: /status-user/
    controller: App\Controller\UserController::statusUser
    #condition: 'request.isXmlHttpRequest()'

delete_user:
    path: /delete-user/
    controller: App\Controller\UserController::deleteUser
    #condition: 'request.isXmlHttpRequest()'

password_user:
    path: /password-user/
    controller: App\Controller\UserController::passwordUser
    #condition: 'request.isXmlHttpRequest()'

user_new:
    path: /user-new/
    controller: App\Controller\RegistrationController::userNew

user_create:
    path: /user-create/
    controller: App\Controller\RegistrationController::userCreate

#
# ONLINE
#

payment_index_stripe:
    path: /payment-index-stripe
    controller: App\Controller\OnlineController::index
    #methods: [POST]

online_charge_credit_card:
    path: /online-charge-credit-card
    controller: App\Controller\OnlineController::chargeCreditCard
    methods: [POST]

online_get_charge:
    path: /online-get-charge
    controller: App\Controller\OnlineController::onlineGetCharge
    methods: [POST]

online_payment_refund:
    path: /online-payment-refund
    controller: App\Controller\OnlineController::onlinePaymentRefund
    #methods: [POST]

refund_index_stripe:
    path: /refund-index-stripe
    controller: App\Controller\OnlineController::refund
    methods: [POST]

logs_stripe:
    path: /payment-logs
    controller: App\Controller\OnlineController::paymentLogs
    methods: [POST]

set_payment:
    path: /set-stripe
    controller: App\Controller\OnlineController::setPayment
    methods: [POST]
